apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name  }}-configmap
data:
  myvalue: "Hello World" 
  {{- $relname := .Release.Name -}}
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end  }}
  release: {{ $relname }} 
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
    - {{ $index }}: {{ $topping }}
    {{- end }}
